services:
  ci:
    image: kcov/kcov
    security_opt:
      - seccomp=unconfined
    volumes:
      - .:/source
    working_dir: /source
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
    entrypoint: /bin/bash
    command:
      - -c
      - ./script/ci.sh --ci
