---
ignored:
  - DL3003  # Use WORKDIR to switch to a directory
  - DL3004  # Do not use sudo (we need it for user setup)
  - DL3006  # Always tag the version of an image explicitly
  - DL3007  # Using latest is prone to errors
  - DL3008  # Pin versions in apt get install
  - DL3013  # Pin versions in pip install
  - DL3018  # Pin versions in apk add
  - DL3046  # useradd without flag -l
  - DL4006  # Set SHELL option -o pipefail (alpine stages use default shell)

