name: Main CI/CD Pipeline
run-name: ${{ github.actor }} triggered CI/CD on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  call-unit-test:
    permissions:
      contents: read
    uses: ./.github/workflows/test-worker.yaml
    secrets: inherit
